---
- name: Setup production
  become: yes
  become_user: root
  command: snova setup production {{ saps_user }} --yes
  args:
    chdir: '{{ snova_path }}'

- name: Setup Sudoers
  become: yes
  become_user: root
  command: snova setup sudoers {{ saps_user }}
  args:
    chdir: '{{ snova_path }}'

- name: Set correct permissions on snova.log
  file:
    path: '{{ snova_path }}/logs/snova.log'
    owner: '{{ saps_user }}'
    group: '{{ saps_user }}'
  become: yes
  become_user: root

- name: Restart the snova
  command: snova restart
  args:
    chdir: '{{ snova_path }}'
...