---
- name: Install deps
  yum:
    name:
      - policycoreutils-python
      - selinux-policy-devel
    state: present
  when: ansible_distribution == 'CentOS'

- name: Check enabled SELinux modules
  shell: semanage module -l
  register: enabled_modules
  when: ansible_distribution == 'CentOS'

- name: Copy saps_selinux policy
  copy: src=saps_selinux.te dest=/root/saps_selinux.te
  register: dest_saps_selinux_te
  when: ansible_distribution == 'CentOS'

- name: Compile saps_selinux policy
  shell: "make -f /usr/share/selinux/devel/Makefile saps_selinux.pp && semodule -i saps_selinux.pp"
  args:
    chdir: /root/
  when: "ansible_distribution == 'CentOS' and enabled_modules.stdout.find('saps_selinux') == -1 or dest_saps_selinux_te.changed"
...